services:
  db:
    image: postgres
    container_name: rehearsal-api-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kez
      POSTGRES_PASSWORD: kezanwar
      POSTGRES_DB: rehearsal
    volumes:
      - rehearsal-api-postgres:/var/lib/postgresql/data

volumes:
  rehearsal-api-postgres:
